require:
  - rubocop_method_order

AllCops:
  Exclude:
    - bin/bundle
    - node_modules/**/*
  TargetRubyVersion: 2.4

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: false

Layout/EmptyLinesAroundArguments:
  Enabled: false # disabled as current implimentation is buggy

Metrics/BlockLength:
  Exclude:
    - test/**/*_test.rb

Metrics/ClassLength:
  Exclude:
    - test/**/*_test.rb

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Exclude:
    - test/**/*_test.rb

Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*_test.rb

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/MethodOrder:
  Exclude:
    - test/**/*_test.rb

Style/RegexpLiteral:
  AllowInnerSlashes: true
  EnforcedStyle: slashes

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets
